version: "3.8"

services:
  currency-web-api:
    container_name: currency-web-api
    image: imckify/currency-web-app:latest
    platform: "linux/amd64"
    build:
      context: https://imckify:${GITHUB_SECRET:-YOUR_GITHUB_PERSONAL_ACCESS_TOKEN}@github.com/iMckify/${REPO:-currency-converter}.git#${BRANCH:-main}:${APP:-backend}
      dockerfile: ./Dockerfile
      args:
        github_secret: ${GITHUB_SECRET:-YOUR_GITHUB_PERSONAL_ACCESS_TOKEN}
        repo: ${REPO:-currency-converter}
        branch: ${BRANCH:-main}
        app: ${APP:-backend}
    ports:
      - "8080:8080"
    network_mode: host