export const API_CALL_BEGIN = 'API_CALL_BEGIN'
export const API_CALL_ERROR = 'API_CALL_ERROR'

export const CLEAR_SELECTED = 'CLEAR_SELECTED'

// USERS
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const LOGOUT = 'LOGOUT'

// CRUD
export function GET_CRUD_ALL_FOR_INVESTOR_RESPONSE(ENTITY_NAME) {
	return `GET_${ENTITY_NAME}_ALL_FOR_INVESTOR_RESPONSE`
}

export function GET_CRUD_ALL_RESPONSE(ENTITY_NAME) {
	return `GET_${ENTITY_NAME}_ALL_RESPONSE`
}

export function GET_CRUD_RESPONSE(ENTITY_NAME) {
	return `GET_${ENTITY_NAME}_RESPONSE`
}

export function ADD_CRUD_RESPONSE(ENTITY_NAME) {
	return `ADD_${ENTITY_NAME}_RESPONSE`
}

export function UPDATE_CRUD_RESPONSE(ENTITY_NAME) {
	return `UPDATE_${ENTITY_NAME}_RESPONSE`
}

export function DELETE_CRUD_RESPONSE(ENTITY_NAME) {
	return `DELETE_${ENTITY_NAME}_RESPONSE`
}

// Administrator
export const GET_CRUD_ALL_FOR_ADMINISTRATOR_UNAPPROVED_RESPONSE = `GET_Requests_ALL_FOR_ADMINISTRATOR_UNAPPROVED_RESPONSE`

export const GET_CIK_TICKER_PAIRS_ALL_FILES_RESPONSE = `GET_CikTickerPairs_ALL_RESPONSE`
