spring:
  datasource:
#    url: jdbc:h2:file:~/h2/lbDB
    url: jdbc:h2:mem:lbDB
    username: root
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        globally_quoted_identifiers: true # escape reserved keywords

  # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: create-drop # none forbids Hibernate to manage DB. Structure and data must be imported from scripts

  h2:
    console:
      enabled: true
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  # for remote access change server.address from localhost to 0.0.0.0
server:
  address: 0.0.0.0
  port: 8080
  error:
    include-message: always

  # external APIs
api:
  lb:
    current: https://www.lb.lt/webservices/FxRates/FxRates.asmx/getCurrentFxRates?tp=eu
    history: https://www.lb.lt/webservices/FxRates/FxRates.asmx/getFxRatesForCurrency?tp=EU&ccy={0}&dtFrom={1}&dtTo={2}